# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 362ae662bd4e6591c30d86b2d830456c68804cff55bfeb093f249ad013e4e560ba0ef071e3ed0244f019cf22a91eaa584bdce322e1aeb33877c2131d18694f14

test:
  secret_key_base: f824bde53dee335266def369bbb081f5e1ca78c59637a2eed552bfa07b862755950df9967dbb51b10902d585cdb1eb34d13af027c3b724bf0e1544503114c2a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
